### ISSUE TITLE
yarn add not working

### ISSUE THREAD

**Issue by SARVESH-THE-dev** [atlj/react-native-background-remover#1]
error Error: https://registry.yarnpkg.com/react-native-background-remover: Not found ,
how can i use with expo

**Comment by mfik** [comment]
Same here. You can add with :  yarn add atlj/react-native-background-remover

**Comment by atlj** [comment]
Hey, I haven't published this package to npm. That's why `yarn add` or `npm add` doesn't work for you. I can publish it if you need this functionality should I?

**Comment by atlj** [comment]
Also regarding Expo, you should be able to add this package to an Expo app and it should work just fine in theory. But you won't be able to use Expo Go and will need the [Expo Dev Client](https://docs.expo.dev/versions/latest/sdk/dev-client/).

**Comment by atlj** [comment]
Folks, I've published the library. You can now install it using `yarn add react-native-background-remover` or `npm install react-native-background-remover`
Here is the link to the npm page: https://www.npmjs.com/package/react-native-background-remover

**Comment by SARVESH-THE-dev** [comment]
THANKS A LOT
