### ISSUE TITLE
Support of a expo plugin

### ISSUE THREAD

**Issue by srivastava9** [atlj/react-native-background-remover#3]
Hey @atlj , Thanks for working on this.
Actually I am working on a react native project managed with expo. So would need Expo plugin for this so that this can be integrated with that

Also Can we integrate this with frame processors in react-native-vision-camera , thus removing background in real time. 
Using https://developers.google.com/ml-kit/vision/selfie-segmentation

**Comment by srivastava9** [comment]
Just for context, if I am building using expo 
getting this error 
` CompileC /Users/adityasrivastava/Library/Developer/Xcode/DerivedData/Flick-aoiwuxlbeajynpebbxdiwadadvoo/Build/Intermediates.noindex/ArchiveIntermediates/Flick/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/ReactNativeBackgroundRemover.build/Objects-normal/arm64/ReactNativeBackgroundRemover-de3c9b6fe319e612257d01405e5fc61a.o /var/folders/fm/r_txqvws25n592djff8svsdh0000gn/T/eas-build-local-nodejs/ce814545-2ed4-4a4a-b925-96aa4f173c13/build/node_modules/react-native-background-remover/ios/ReactNativeBackgroundRemover.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ReactNativeBackgroundRemover' from project 'Pods')`

**Comment by atlj** [comment]
Hey #8 added an Expo example. This means I've verified that the library works with Expo.
